
  CREATE TABLE "SYSTEM"."CONTACT" 
   (	"ID" NUMBER(10,0) NOT NULL ENABLE, 
	"NOMBRE" VARCHAR2(25 BYTE) NOT NULL ENABLE, 
	"SEXO" VARCHAR2(12 BYTE) NOT NULL ENABLE, 
	"IDIOMA" VARCHAR2(30 BYTE) NOT NULL ENABLE, 
	"COMENTARIO" VARCHAR2(45 BYTE) NOT NULL ENABLE, 
	 CONSTRAINT "CONTACT_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
 
